name: Stamp Colab Run Time

on:
  workflow_run:
    workflows:
      - Stamp notebook and advance colab-latest
      - Promote notebook to colab-stable
    types: [completed]
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

permissions:
  contents: write
  actions: read

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch latest successful run times
        id: fetch
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 - <<'PY'
import os, json, urllib.request
repo = os.environ['GH_REPO']
token = os.environ['GH_TOKEN']
def latest(workflow_file):
    url=f'https://api.github.com/repos/{repo}/actions/workflows/{workflow_file}/runs?status=success&per_page=1'
    req=urllib.request.Request(url, headers={'Authorization': f'Bearer {token}','Accept':'application/vnd.github+json'})
    with urllib.request.urlopen(req) as r:
        data=json.load(r)
    runs = data.get('workflow_runs', [])
    return runs[0].get('updated_at','N/A') if runs else 'N/A'
latest_ts = latest('update-colab-latest.yml')
stable_ts = latest('promote-colab-stable.yml')
print('latest=', latest_ts)
print('stable=', stable_ts)
with open(os.environ['GITHUB_OUTPUT'],'a') as f:
    f.write(f"latest={latest_ts}\n")
    f.write(f"stable={stable_ts}\n")
PY

      - name: Update timestamps in README
        env:
          LATEST_TS: ${{ steps.fetch.outputs.latest }}
          STABLE_TS: ${{ steps.fetch.outputs.stable }}
        run: |
          python3 - <<'PY'
import os, re
pth = 'README.md'
txt = open(pth,'r',encoding='utf-8').read()
latest = os.environ.get('LATEST_TS','N/A')
stable = os.environ.get('STABLE_TS','N/A')
def sub(marker, stamp, s):
    pattern = rf"(<!-- {marker}:START -->)(.*?)(<!-- {marker}:END -->)"
    return re.sub(pattern, rf"\\1{stamp}\\3", s, flags=re.S)
new = sub('COLAB_LATEST_RUN', latest, txt)
new = sub('COLAB_STABLE_RUN', stable, new)
if new != txt:
    open(pth,'w',encoding='utf-8').write(new)
    print('Updated timestamps: latest=', latest, 'stable=', stable)
else:
    print('No changes needed')
PY

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add README.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "docs: update Colab workflow timestamps in README [skip ci]"
            git push
          fi
