name: Stamp notebook and advance colab-latest

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  stamp-and-advance:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    concurrency:
      group: colab-stamp-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Stamp notebook header + links
        run: |
          python scripts/patch_notebook.py
      - name: Commit stamped changes (if any)
        run: |
          set -e
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "ci: stamp notebook header + links [skip ci]"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi
      - name: Move colab-latest to current HEAD
        run: |
          git push origin HEAD:refs/heads/colab-latest
